# Generated by Django 5.2.14 on 2026-06-12 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_representatives', '0003_remove_salesrepresentative_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesrepresentative',
            name='email',
            field=models.EmailField(default='abc@gmail.com', max_length=254, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='salesrepresentative',
            name='password',
            field=models.CharField(default='abcd@gmail.com', max_length=128),
            preserve_default=False,
        ),
    ]
